name: ci-cd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:            
  test_push_deploy:
    runs-on: ubuntu-20.04
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

    services:
          mysql:
            image: mysql:5.7
            env:
              MYSQL_ROOT_PASSWORD: 12345
              MYSQL_DATABASE: restaurants
            ports:
            - 3307:3306

          back: 
            image: alexanderukhanov/back
            ports:
            - 3001:3001

    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 16.15.0
            
#         - name: curl result
#           run: curl --fail HEAD  http://localhost:3001
          
        - name: docker services
          run: |
            sleep 30
            sudo docker ps -a
            curl HEAD  http://localhost:3001
      
        - name: test
          run: |
            yarn install 
            yarn start &
            sleep 200
            yarn test

        - name: push
          run: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker build -t alexanderukhanov/front .
            docker push alexanderukhanov/front

        - name: deploy
          uses: appleboy/ssh-action@master
          with:
            host: $SSH_HOST
            username: $SSH_USERNAME
            key: $SSH_KEY
            script: touch success_front.txt
